#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# User Acceptance Test Script for Feature 3: Merge Consecutive Dives Wizard
#
# This script documents the manual testing procedures for the merge consecutive
# dives wizard feature. Follow these steps to validate the feature works correctly.

echo "=========================================="
echo "UAT: Feature 3 - Merge Consecutive Dives"
echo "=========================================="
echo ""
echo "Prerequisites:"
echo "  1. Subsurface is built and running"
echo "  2. You have a dive log with multiple dives"
echo "  3. Some dives should be within 60 minutes of each other"
echo ""
echo "Test Setup:"
echo "  Create or load a test dive log with the following scenarios:"
echo "    - Two dives 30 minutes apart (should be detected)"
echo "    - Two dives 90 minutes apart (should NOT be detected with default threshold)"
echo "    - Three dives all within 60 minutes (should show as pairs)"
echo "    - A single dive with no nearby dives"
echo ""

echo "==========================================="
echo "Test Case 1: Access the Wizard"
echo "==========================================="
echo ""
echo "Steps:"
echo "  1. Open Subsurface with a loaded dive log"
echo "  2. Navigate to Log menu"
echo "  3. Click 'Merge consecutive dives'"
echo ""
echo "Expected Result:"
echo "  - The 'Merge consecutive dives' wizard dialog opens"
echo "  - Dialog shows description text explaining the feature"
echo "  - Default threshold is set to 60 minutes"
echo "  - 'Detect consecutive dives' button is visible"
echo ""
echo "Pass: [ ]  Fail: [ ]  Notes: _________________________________"
echo ""

echo "==========================================="
echo "Test Case 2: Detect Consecutive Dives"
echo "==========================================="
echo ""
echo "Steps:"
echo "  1. In the wizard, ensure threshold is set to 60 minutes"
echo "  2. Click 'Detect consecutive dives' button"
echo ""
echo "Expected Result:"
echo "  - Table populates with detected dive pairs"
echo "  - Each row shows:"
echo "    - Checkbox (checked by default)"
echo "    - First dive info (number, date, depth, duration)"
echo "    - Second dive info (number, date, depth, duration)"
echo "    - Surface interval between dives"
echo "    - Combined duration if merged"
echo "  - Status shows count of pairs found"
echo ""
echo "Pass: [ ]  Fail: [ ]  Notes: _________________________________"
echo ""

echo "==========================================="
echo "Test Case 3: Change Threshold"
echo "==========================================="
echo ""
echo "Steps:"
echo "  1. Change threshold to 30 minutes"
echo "  2. Click 'Detect consecutive dives'"
echo "  3. Note the number of pairs found"
echo "  4. Change threshold to 90 minutes"
echo "  5. Click 'Detect consecutive dives'"
echo "  6. Compare results"
echo ""
echo "Expected Result:"
echo "  - Lower threshold finds fewer pairs"
echo "  - Higher threshold finds more pairs"
echo "  - Results update correctly when re-detecting"
echo ""
echo "Pass: [ ]  Fail: [ ]  Notes: _________________________________"
echo ""

echo "==========================================="
echo "Test Case 4: Select/Deselect Pairs"
echo "==========================================="
echo ""
echo "Steps:"
echo "  1. Detect dives with multiple pairs"
echo "  2. Uncheck one or more pairs manually"
echo "  3. Click 'Select all' button"
echo "  4. Click 'Select none' button"
echo "  5. Manually select specific pairs"
echo ""
echo "Expected Result:"
echo "  - Individual checkboxes toggle correctly"
echo "  - 'Select all' checks all checkboxes"
echo "  - 'Select none' unchecks all checkboxes"
echo "  - Selected count updates in real-time"
echo "  - OK button disabled when no pairs selected"
echo "  - OK button enabled when at least one pair selected"
echo ""
echo "Pass: [ ]  Fail: [ ]  Notes: _________________________________"
echo ""

echo "==========================================="
echo "Test Case 5: Merge Selected Dives"
echo "==========================================="
echo ""
echo "Steps:"
echo "  1. Detect dives and select one or more pairs"
echo "  2. Click OK"
echo "  3. Confirm the merge when prompted"
echo "  4. Check the dive list"
echo ""
echo "Expected Result:"
echo "  - Confirmation dialog appears with count of pairs to merge"
echo "  - After confirming, selected pairs are merged"
echo "  - Merged dive appears in dive list"
echo "  - Original dives are removed"
echo "  - Merged dive has combined profile data"
echo "  - Merged dive takes earlier dive number (if numbered)"
echo ""
echo "Pass: [ ]  Fail: [ ]  Notes: _________________________________"
echo ""

echo "==========================================="
echo "Test Case 6: Undo Merge"
echo "==========================================="
echo ""
echo "Steps:"
echo "  1. After merging dives, use Edit > Undo (Ctrl+Z)"
echo ""
echo "Expected Result:"
echo "  - Merge is undone"
echo "  - Original separate dives are restored"
echo "  - Dive list shows original dives again"
echo ""
echo "Pass: [ ]  Fail: [ ]  Notes: _________________________________"
echo ""

echo "==========================================="
echo "Test Case 7: Cancel Operation"
echo "==========================================="
echo ""
echo "Steps:"
echo "  1. Open the wizard"
echo "  2. Detect dives"
echo "  3. Select some pairs"
echo "  4. Click Cancel"
echo ""
echo "Expected Result:"
echo "  - Wizard closes"
echo "  - No dives are merged"
echo "  - Dive list unchanged"
echo ""
echo "Pass: [ ]  Fail: [ ]  Notes: _________________________________"
echo ""

echo "==========================================="
echo "Test Case 8: No Consecutive Dives"
echo "==========================================="
echo ""
echo "Steps:"
echo "  1. Load a dive log where all dives are far apart"
echo "  2. Open the wizard"
echo "  3. Click detect"
echo ""
echo "Expected Result:"
echo "  - Message indicates no consecutive dives found"
echo "  - Table is empty"
echo "  - OK button is disabled"
echo ""
echo "Pass: [ ]  Fail: [ ]  Notes: _________________________________"
echo ""

echo "==========================================="
echo "Test Case 9: Keyboard Shortcuts"
echo "==========================================="
echo ""
echo "Steps:"
echo "  1. Open the wizard"
echo "  2. Press Ctrl+W"
echo ""
echo "Expected Result:"
echo "  - Wizard closes"
echo ""
echo "Pass: [ ]  Fail: [ ]  Notes: _________________________________"
echo ""

echo "==========================================="
echo "Summary"
echo "==========================================="
echo ""
echo "Total Tests: 9"
echo "Tests Passed: ___"
echo "Tests Failed: ___"
echo ""
echo "Tester Name: _______________________"
echo "Date: _______________________"
echo "Build Version: _______________________"
echo ""
echo "Additional Notes:"
echo "_____________________________________________________"
echo "_____________________________________________________"
echo "_____________________________________________________"
echo ""
