#!/bin/bash
# UAT Test Script for Feature 1: Consolidate Nearby Dive Sites
# This script guides manual testing of the dive site consolidation feature.

echo "========================================"
echo "UAT Test: Consolidate Nearby Dive Sites"
echo "========================================"
echo ""
echo "Prerequisites:"
echo "  - Subsurface application built and running"
echo "  - Test dive log with multiple dive sites (some nearby, some distant)"
echo ""

echo "----------------------------------------"
echo "Test 1: Access the Feature"
echo "----------------------------------------"
echo "Steps:"
echo "  1. Open Subsurface"
echo "  2. Load a dive log with dive sites that have GPS coordinates"
echo "  3. Go to Log menu -> Dive Site Management"
echo "  4. Click 'Consolidate dive sites...' button"
echo ""
echo "Expected: A dialog appears with distance threshold input and tree view"
echo ""
read -p "Press Enter to continue to next test..."

echo "----------------------------------------"
echo "Test 2: Distance Threshold Units"
echo "----------------------------------------"
echo "Steps:"
echo "  1. Check the distance threshold input field"
echo "  2. Verify the unit label (m for metric, ft for imperial)"
echo "  3. Open Preferences and change units if needed to test both"
echo ""
echo "Expected:"
echo "  - Default threshold: 10m (metric) or ~33ft (imperial)"
echo "  - Unit label reflects user preference"
echo ""
read -p "Press Enter to continue to next test..."

echo "----------------------------------------"
echo "Test 3: Scan for Groups"
echo "----------------------------------------"
echo "Steps:"
echo "  1. Leave default distance threshold (10m/33ft)"
echo "  2. Click 'Scan for nearby sites' button"
echo "  3. Observe the tree view"
echo ""
echo "Expected:"
echo "  - Groups of nearby sites appear in tree view"
echo "  - Each group shows number of sites in header"
echo "  - Sites show name, dive count, and distance from primary"
echo "  - Primary site is bolded and marked '(Primary)'"
echo ""
read -p "Press Enter to continue to next test..."

echo "----------------------------------------"
echo "Test 4: Change Distance Threshold"
echo "----------------------------------------"
echo "Steps:"
echo "  1. Increase distance threshold (e.g., to 50m)"
echo "  2. Click 'Scan for nearby sites' again"
echo "  3. Observe changes in groupings"
echo ""
echo "Expected:"
echo "  - More sites may be grouped together with larger threshold"
echo "  - Previously separate groups may merge"
echo ""
read -p "Press Enter to continue to next test..."

echo "----------------------------------------"
echo "Test 5: Set Primary Site"
echo "----------------------------------------"
echo "Steps:"
echo "  1. Expand a group in the tree view"
echo "  2. Select a non-primary site"
echo "  3. Click 'Set as Primary' button"
echo ""
echo "Expected:"
echo "  - Selected site becomes bold with '(Primary)' marker"
echo "  - Previous primary site loses bold/marker"
echo "  - Distances are recalculated relative to new primary"
echo ""
read -p "Press Enter to continue to next test..."

echo "----------------------------------------"
echo "Test 6: Consolidate Selected Group"
echo "----------------------------------------"
echo "Steps:"
echo "  1. Select a group in the tree view"
echo "  2. Click 'Consolidate Selected Group' button"
echo "  3. Read confirmation dialog"
echo "  4. Click 'Yes' to proceed"
echo ""
echo "Expected:"
echo "  - Confirmation dialog shows site count and primary name"
echo "  - After confirmation, group disappears from tree"
echo "  - Prompt appears to purge unused sites"
echo ""
read -p "Press Enter to continue to next test..."

echo "----------------------------------------"
echo "Test 7: Verify Merge Result"
echo "----------------------------------------"
echo "Steps:"
echo "  1. Close the consolidation dialog"
echo "  2. Check Dive Site Management list"
echo "  3. Verify dives were moved to primary site"
echo "  4. Test Undo (Ctrl+Z / Cmd+Z)"
echo ""
echo "Expected:"
echo "  - Merged sites still exist but have no dives"
echo "  - Primary site has all dives from the group"
echo "  - Undo restores original state"
echo ""
read -p "Press Enter to continue to next test..."

echo "----------------------------------------"
echo "Test 8: Consolidate All Groups"
echo "----------------------------------------"
echo "Steps:"
echo "  1. Reopen consolidation dialog"
echo "  2. Scan to find multiple groups"
echo "  3. Click 'Consolidate All Groups' button"
echo "  4. Confirm the operation"
echo ""
echo "Expected:"
echo "  - Confirmation shows total groups and sites"
echo "  - All groups are consolidated"
echo "  - Tree view becomes empty"
echo "  - Purge unused sites prompt appears"
echo ""
read -p "Press Enter to continue to next test..."

echo "----------------------------------------"
echo "Test 9: Purge Unused Sites"
echo "----------------------------------------"
echo "Steps:"
echo "  1. After consolidation, click 'Yes' on purge prompt"
echo "  2. Check Dive Site Management list"
echo ""
echo "Expected:"
echo "  - Merged (empty) sites are removed"
echo "  - Only primary sites with dives remain"
echo ""
read -p "Press Enter to continue to next test..."

echo "----------------------------------------"
echo "Test 10: Edge Cases"
echo "----------------------------------------"
echo "Steps:"
echo "  1. Test with dive log that has no GPS coordinates"
echo "  2. Test with only one dive site"
echo "  3. Test with all sites far apart (no groups)"
echo ""
echo "Expected:"
echo "  - No groups found for sites without GPS"
echo "  - No groups for single site"
echo "  - No groups when all sites are distant"
echo ""
echo ""

echo "========================================"
echo "UAT Test Complete"
echo "========================================"
echo ""
echo "Test Results Summary:"
echo "  [ ] Test 1: Access the Feature"
echo "  [ ] Test 2: Distance Threshold Units"
echo "  [ ] Test 3: Scan for Groups"
echo "  [ ] Test 4: Change Distance Threshold"
echo "  [ ] Test 5: Set Primary Site"
echo "  [ ] Test 6: Consolidate Selected Group"
echo "  [ ] Test 7: Verify Merge Result"
echo "  [ ] Test 8: Consolidate All Groups"
echo "  [ ] Test 9: Purge Unused Sites"
echo "  [ ] Test 10: Edge Cases"
echo ""
echo "Mark [X] for passed tests, [F] for failed tests"
echo "Document any issues found in a separate report"
